##################
# Primary Clocks #
##################

# Differential input clock from SI570 clock synthesizer on ZC702
# Constrained to 148.5MHz (1080p60 video resolution)
create_clock -period 6.734 -name video_clk [get_ports video_clk_p]

####################
# Generated Clocks #
####################

# Rename auto-generated clocks from MMCM
create_generated_clock -name clk_75mhz [get_pins system_top_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT0]
create_generated_clock -name clk_150mhz [get_pins system_top_i/clk_wiz_1/inst/mmcm_adv_inst/CLKOUT1]

################
# Clock Groups #
################

# video_clk is generated by SI570 clock synthesizer and clk_75mhz/clk_150mhz by MMCM
# There is no known phase relationship, hence they are treated  as asynchronous
set_clock_groups -name async_clks -asynchronous -group {clk_75mhz clk_150mhz} -group video_clk

########################
# Physical Constraints #
########################

# Clock Synthesizer (SI570) on ZC706
set_property PACKAGE_PIN AF14 [get_ports video_clk_p]
set_property PACKAGE_PIN AG14 [get_ports video_clk_n]
set_property IOSTANDARD LVDS_25 [get_ports video_clk_*]
set_property DIFF_TERM TRUE [get_ports video_clk_*]

# HDMI Output (ADV7511) on ZC706
set_property PACKAGE_PIN P28 [get_ports hdmio_clk]
set_property PACKAGE_PIN U21 [get_ports hdmio_vsync]
set_property PACKAGE_PIN R22 [get_ports hdmio_hsync]
set_property PACKAGE_PIN V24 [get_ports hdmio_de]
set_property PACKAGE_PIN AC23 [get_ports hdmio_int_b]
set_property PACKAGE_PIN AD26 [get_ports {hdmio_data[0]}]
set_property PACKAGE_PIN AB26 [get_ports {hdmio_data[1]}]
set_property PACKAGE_PIN AA28 [get_ports {hdmio_data[2]}]
set_property PACKAGE_PIN AC26 [get_ports {hdmio_data[3]}]
set_property PACKAGE_PIN AE30 [get_ports {hdmio_data[4]}]
set_property PACKAGE_PIN Y25 [get_ports {hdmio_data[5]}]
set_property PACKAGE_PIN AA29 [get_ports {hdmio_data[6]}]
set_property PACKAGE_PIN AD30 [get_ports {hdmio_data[7]}]
set_property PACKAGE_PIN Y28 [get_ports {hdmio_data[8]}]
set_property PACKAGE_PIN AF28 [get_ports {hdmio_data[9]}]
set_property PACKAGE_PIN V22 [get_ports {hdmio_data[10]}]
set_property PACKAGE_PIN AA27 [get_ports {hdmio_data[11]}]
set_property PACKAGE_PIN U22 [get_ports {hdmio_data[12]}]
set_property PACKAGE_PIN N28 [get_ports {hdmio_data[13]}]
set_property PACKAGE_PIN V21 [get_ports {hdmio_data[14]}]
set_property PACKAGE_PIN AC22 [get_ports {hdmio_data[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports hdmio_*]
set_property IOB TRUE [get_cells -hierarchical vid_out_formatter_i/in_*_mux_reg*]

## I2C 2 Chain on FMC-IMAGEON
#set_property PACKAGE_PIN AE18 [get_ports iic_scl_io]
#set_property PACKAGE_PIN AE17 [get_ports iic_sda_io]
#set_property PACKAGE_PIN AG15 [get_ports iic_rst]
#set_property IOSTANDARD LVCMOS25 [get_ports iic_*]

## VITA Interface on FMC-IMAGEON
#set_property PACKAGE_PIN AH17 [get_ports io_vita_clk_pll]
#set_property PACKAGE_PIN AG16 [get_ports io_vita_reset_n]
#set_property PACKAGE_PIN AH16 [get_ports io_vita_trigger[2]]
#set_property PACKAGE_PIN AF18 [get_ports io_vita_trigger[1]]
#set_property PACKAGE_PIN AF17 [get_ports io_vita_trigger[0]]
#set_property PACKAGE_PIN AB15 [get_ports io_vita_monitor[0]]
#set_property PACKAGE_PIN AB14 [get_ports io_vita_monitor[1]]
#set_property PACKAGE_PIN AD16 [get_ports io_vita_spi_sclk]
#set_property PACKAGE_PIN AD15 [get_ports io_vita_spi_ssel_n]
#set_property PACKAGE_PIN AJ16 [get_ports io_vita_spi_mosi]
#set_property PACKAGE_PIN AK16 [get_ports io_vita_spi_miso]
#set_property PACKAGE_PIN AE13 [get_ports io_vita_clk_out_p]
#set_property PACKAGE_PIN AF13 [get_ports io_vita_clk_out_n]
#set_property PACKAGE_PIN AC14 [get_ports io_vita_sync_p]
#set_property PACKAGE_PIN AC13 [get_ports io_vita_sync_n]
#set_property PACKAGE_PIN AH14 [get_ports io_vita_data_p[0]]
#set_property PACKAGE_PIN AH13 [get_ports io_vita_data_n[0]]
#set_property PACKAGE_PIN AA15 [get_ports io_vita_data_p[1]]
#set_property PACKAGE_PIN AA14 [get_ports io_vita_data_n[1]]
#set_property PACKAGE_PIN AD14 [get_ports io_vita_data_p[2]]
#set_property PACKAGE_PIN AD13 [get_ports io_vita_data_n[2]]
#set_property PACKAGE_PIN AE16 [get_ports io_vita_data_p[3]]
#set_property PACKAGE_PIN AE15 [get_ports io_vita_data_n[3]]
#set_property PACKAGE_PIN AJ15 [get_ports io_vita_data_p[4]]
#set_property PACKAGE_PIN AK15 [get_ports io_vita_data_n[4]]
#set_property PACKAGE_PIN AB12 [get_ports io_vita_data_p[5]]
#set_property PACKAGE_PIN AC12 [get_ports io_vita_data_n[5]]
#set_property PACKAGE_PIN AG12 [get_ports io_vita_data_p[6]]
#set_property PACKAGE_PIN AH12 [get_ports io_vita_data_n[6]]
#set_property PACKAGE_PIN AE12 [get_ports io_vita_data_p[7]]
#set_property PACKAGE_PIN AF12 [get_ports io_vita_data_n[7]]

#set_property IOSTANDARD LVCMOS25 [get_ports io_vita_clk_pll]
#set_property IOSTANDARD LVCMOS25 [get_ports io_vita_reset_n]
#set_property IOSTANDARD LVCMOS25 [get_ports io_vita_trigger*]
#set_property IOSTANDARD LVCMOS25 [get_ports io_vita_monitor*]
#set_property IOSTANDARD LVCMOS25 [get_ports io_vita_spi_*]

#set_property IOSTANDARD LVDS_25 [get_ports io_vita_clk_out_*]
#set_property IOSTANDARD LVDS_25 [get_ports io_vita_sync_*]
#set_property IOSTANDARD LVDS_25 [get_ports io_vita_data_*]

#set_property IOSTANDARD LVCMOS25 [get_ports io_vita_data_p[4]];
#set_property IOSTANDARD LVCMOS25 [get_ports io_vita_data_n[4]];
#set_property IOSTANDARD LVCMOS25 [get_ports io_vita_data_p[5]];
#set_property IOSTANDARD LVCMOS25 [get_ports io_vita_data_n[5]];
#set_property IOSTANDARD LVCMOS25 [get_ports io_vita_data_p[6]];
#set_property IOSTANDARD LVCMOS25 [get_ports io_vita_data_n[6]];
#set_property IOSTANDARD LVCMOS25 [get_ports io_vita_data_p[7]];
#set_property IOSTANDARD LVCMOS25 [get_ports io_vita_data_n[7]];

#set_property DIFF_TERM true [get_ports io_vita_clk_out_*]
#set_property DIFF_TERM true [get_ports io_vita_sync_*]
#set_property DIFF_TERM true [get_ports io_vita_data_*]

## Video Clock Synthesizer on FMC-IMAGEON
#set_property PACKAGE_PIN AG17 [get_ports clk_in1];
#set_property IOSTANDARD LVCMOS25 [get_ports clk_in1]
